### ISSUE TITLE
Using Space's teams as user groups

### ISSUE THREAD

**Issue by DaviPtrs** [lensapp/bored-agent#68]
Would be great if I could just create a Team, put some user on it and create a ClusterRoleBinding for the team's group, instead of adding the users on the RBAC separately. I don't know if this feature already exists but I didn't found about it on the docs.

**Comment by jakolehm** [comment]
You can use teams already in bindings:

```
- kind: Group
  name: lens-spaces:<team-name>
  apiGroup: rbac.authorization.k8s.io
```

**Comment by DaviPtrs** [comment]
Awesome, thanks!
